spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/denodo
    username: api_denodo
    password: P@ssw0rdironsin0

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-test-query: SELECT 1

server:
  port: 8080

file:
  upload:
    dir: D:/workspace/denodo-api/uploads
    serve-static: true

logging:
  level:
    org.springframework.jdbc: info
    com.denodo.platform.api.post.mapper: debug